name: FastAPI Calculator CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        pytest tests/test_operations.py -v --cov=app/operations --cov-report=xml
    
    - name: Run integration tests
      run: |
        pytest tests/test_integration.py -v
    
    - name: Lint with flake8 (non-blocking)
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics || true
    
    - name: Format check with black (non-blocking)
      run: |
        black --check . || true
    
    - name: Sort imports check with isort (non-blocking)
      run: |
        isort --check-only . || true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build application
      run: |
        echo "Application built successfully"
        echo "FastAPI Calculator ready for deployment"
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: fastapi-calculator-build
        path: |
          app/
          templates/
          static/
          main.py
          requirements.txt
          README.md